### PR TITLE
Switch from a Halloween footer to a winter theme

### PR DESCRIPTION
**Pull request by johnotander**
Thought you might be interested in changing seasons :smile_cat: 

* Made the footer background white to represent snow and winter.
* Now using olive links, buttons, and tagline to represent evergreen trees.
* Author related links are changed to gray for a more winter-y feel, as well.

v6tupmu7wikrax8vk9rbbe9lcbl369pmmwcmmguc6ko

### CODE REVIEW

**Comment by johnotander** [comment]
Ping @mrmrs.

**Comment by johnotander** [comment]
Closing as I've noticed you've now removed the holiday footer, :)

**Comment by mrmrs** [comment]
@johnotander - sorry was meaning to comment. Like your christmas theme I had just already started in on my update. I'm not 100% happy with it though and will probably be updating again soon :)

**Comment by johnotander** [comment]
No worries, I think your update looks great.

My only comment on a possible enhancement is I'd consider switching either `the` or `of` colors with `colors` so it is more pronounced being the name of the package and all.

Thanks again for an awesome project.

**Comment by mrmrs** [comment]
@johnotander - working on animating the words. Just trying to be playful in the footer.

**Pull request closed without merging**
